<a href="https://colab.research.google.com/github/mehdimerbah/CompDrugDiscovery/blob/main/DescriptorCalculation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
## Import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import glob
from padelpy import padeldescriptor

## Padel-Descriptors

In [59]:
! wget https://github.com/dataprofessor/padel/raw/main/fingerprints_xml.zip
! unzip fingerprints_xml.zip

--2022-04-26 21:58:49--  https://github.com/dataprofessor/padel/raw/main/fingerprints_xml.zip
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/dataprofessor/padel/main/fingerprints_xml.zip [following]
--2022-04-26 21:58:49--  https://raw.githubusercontent.com/dataprofessor/padel/main/fingerprints_xml.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10871 (11K) [application/zip]
Saving to: ‘fingerprints_xml.zip.1’

fingerprints_xml.zi 100%[===================>]  10.62K  --.-KB/s    in 0s

2022-04-26 21:58:49 (83.2 MB/s) - ‘fingerprints_xml.zip.1’ saved [10871/10871]

Archive:  fingerprints_xml.zip
replace AtomPairs2DFingerprintCount.xml? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: AtomPairs2DFingerprintCount.xml
  inflating: AtomPairs2DFingerprinter.xml
  inflating: EStateFingerprinter.xml
  inflating: ExtendedFingerprinter.xml
  inflating: Fingerprinter.xml
  inflating: GraphOnlyFingerprinter.xml
  inflating: KlekotaRothFingerprintCount.xml
  inflating: KlekotaRothFingerprinter.xml
  inflating: MACCSFingerprinter.xml
  inflating: PubchemFingerprinter.xml
  inflating: SubstructureFingerprintCount.xml
  inflating: SubstructureFingerprinter.xml

In [60]:
bioactivity_DF = pd.read_csv('https://raw.githubusercontent.com/mehdimerbah/CompDrugDiscovery/main/data/normalized_data.csv')

In [61]:
bioactivity_DF.head(10)

,molecule_chembl_id,canonical_smiles,activity_class,MW,LogP,NumHDonors,NumHAcceptors,pIC50
0,CHEMBL372889,Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C(N)=O)ccc21,active,299.286,1.11984,1.0,5.0,7.602060
1,CHEMBL185698,O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21,inactive,421.190,2.66050,0.0,4.0,4.869666
2,CHEMBL188484,O=C1C(=O)N(Cc2cc3ccccc3o2)c2ccc(I)cc21,active,403.175,3.76690,0.0,3.0,7.886057
3,CHEMBL362781,COc1ccc2c(c1)C(=O)C(=O)N2Cc1cc2ccccc2o1,active,307.305,3.17090,0.0,4.0,7.886057
4,CHEMBL191322,O=C1C(=O)N(Cc2cc3ccccc3o2)c2ccc([N+](=O)[O-])cc21,active,322.276,3.07050,0.0,5.0,7.619789
5,CHEMBL426082,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccccc21,inactive,293.347,3.63080,0.0,3.0,4.882397
6,CHEMBL363243,Nc1cccc2c1N(Cc1cc3ccccc3s1)C(=O)C2=O,active,308.362,3.21300,1.0,4.0,7.508638
7,CHEMBL365134,O=C1C(=O)N(Cc2cc3ccccc3s2)c2c(Br)cccc21,active,372.243,4.39330,0.0,3.0,6.008774
8,CHEMBL365677,Cc1cc2c(c([N+](=O)[O-])c1)N(Cc1cc3ccccc3s1)C(=...,active,352.371,3.84742,0.0,5.0,7.408935
9,CHEMBL188811,COc1ccc2c(c1)C(=O)C(=O)N2Cc1cc2ccccc2s1,active,323.373,3.63940,0.0,4.0,7.568636

In [69]:
filtered_DF = bioactivity_DF[['canonical_smiles', 'molecule_chembl_id']]

In [70]:
filtered_DF.head(10)

                                    canonical_smiles molecule_chembl_id
0          Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C(N)=O)ccc21       CHEMBL372889
1            O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21       CHEMBL185698
2             O=C1C(=O)N(Cc2cc3ccccc3o2)c2ccc(I)cc21       CHEMBL188484
3            COc1ccc2c(c1)C(=O)C(=O)N2Cc1cc2ccccc2o1       CHEMBL362781
4  O=C1C(=O)N(Cc2cc3ccccc3o2)c2ccc([N+](=O)[O-])cc21       CHEMBL191322
5                O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccccc21       CHEMBL426082
6               Nc1cccc2c1N(Cc1cc3ccccc3s1)C(=O)C2=O       CHEMBL363243
7            O=C1C(=O)N(Cc2cc3ccccc3s2)c2c(Br)cccc21       CHEMBL365134
8  Cc1cc2c(c([N+](=O)[O-])c1)N(Cc1cc3ccccc3s1)C(=...       CHEMBL365677
9            COc1ccc2c(c1)C(=O)C(=O)N2Cc1cc2ccccc2s1       CHEMBL188811

In [71]:
filtered_DF.to_csv('molecule.smi', sep='\t', index=False, header=False)

In [ ]:
! pip install padelpy

Collecting padelpy
  Downloading padelpy-0.1.11-py2.py3-none-any.whl (20.9 MB)
     |████████████████████████████████| 20.9 MB 1.3 MB/s
Installing collected packages: padelpy
Successfully installed padelpy-0.1.11

In [67]:
xml_files = glob.glob("*.xml")
xml_files.sort()
xml_files

['AtomPairs2DFingerprintCount.xml',
 'AtomPairs2DFingerprinter.xml',
 'EStateFingerprinter.xml',
 'ExtendedFingerprinter.xml',
 'Fingerprinter.xml',
 'GraphOnlyFingerprinter.xml',
 'KlekotaRothFingerprintCount.xml',
 'KlekotaRothFingerprinter.xml',
 'MACCSFingerprinter.xml',
 'PubchemFingerprinter.xml',
 'SubstructureFingerprintCount.xml',
 'SubstructureFingerprinter.xml']

In [68]:
fingerprints = ['AtomPairs2DCount',
 'AtomPairs2D',
 'EState',
 'CDKextended',
 'CDK',
 'CDKgraphonly',
 'KlekotaRothCount',
 'KlekotaRoth',
 'MACCS',
 'PubChem',
 'SubstructureCount',
 'Substructure']

FP_hashmap = dict(zip(fingerprints, xml_files))

In [ ]:
fingerprint = 'Substructure'

fingerprint_output_file = ''.join([fingerprint,'.csv']) #Substructure.csv
fingerprint_descriptortypes = FP_hashmap[fingerprint]

padeldescriptor(mol_dir='molecule.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

In [77]:
features_DF = pd.read_csv(fingerprint_output_file)
features_DF.head(10)

,Name,SubFP1,SubFP2,SubFP3,SubFP4,SubFP5,SubFP6,SubFP7,SubFP8,SubFP9,...,SubFP298,SubFP299,SubFP300,SubFP301,SubFP302,SubFP303,SubFP304,SubFP305,SubFP306,SubFP307
0,CHEMBL185698,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
1,CHEMBL372889,1,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
2,CHEMBL188484,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
3,CHEMBL362781,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
4,CHEMBL426082,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
5,CHEMBL191322,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,0,0,1
6,CHEMBL365134,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
7,CHEMBL363243,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
8,CHEMBL365677,1,0,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,0,0,1
9,CHEMBL188811,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1

In [84]:
features_DF = features_DF.drop(columns=['Name'])
features_DF

,SubFP1,SubFP2,SubFP3,SubFP4,SubFP5,SubFP6,SubFP7,SubFP8,SubFP9,SubFP10,...,SubFP298,SubFP299,SubFP300,SubFP301,SubFP302,SubFP303,SubFP304,SubFP305,SubFP306,SubFP307
0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
1,1,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,1,1,0,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
264,1,0,0,0,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,1
265,1,1,1,1,0,0,0,0,0,0,...,0,0,1,1,0,1,0,0,0,1
266,1,0,1,0,0,0,0,0,0,0,...,0,0,1,1,0,1,0,0,0,1
267,1,1,1,1,1,0,0,0,0,0,...,0,0,1,1,1,1,0,0,0,1

In [88]:
targets = bioactivity_DF['pIC50']
model_input_DF = pd.concat([features_DF, targets], axis = 1)

model_input_DF.head(10)

,SubFP1,SubFP2,SubFP3,SubFP4,SubFP5,SubFP6,SubFP7,SubFP8,SubFP9,SubFP10,...,SubFP299,SubFP300,SubFP301,SubFP302,SubFP303,SubFP304,SubFP305,SubFP306,SubFP307,pIC50
0,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,1,7.602060
1,1,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,1,4.869666
2,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,1,7.886057
3,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,1,7.886057
4,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,1,7.619789
5,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,0,0,0,0,1,4.882397
6,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,1,7.508638
7,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,1,6.008774
8,1,0,0,0,0,0,0,0,0,0,...,1,1,1,1,0,0,0,0,1,7.408935
9,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,1,7.568636

Warning: Total number of columns (308) exceeds max_columns (20) limiting to first (20) columns.

In [90]:
model_input_DF.to_csv('model_data.csv', index = False)